require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NDegreesController do

  # This should return the minimal set of attributes required to create a valid
  # NDegree. As you add validations to NDegree, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NDegreesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all n_degrees as @n_degrees" do
      n_degree = NDegree.create! valid_attributes
      get :index, {}, valid_session
      assigns(:n_degrees).should eq([n_degree])
    end
  end

  describe "GET show" do
    it "assigns the requested n_degree as @n_degree" do
      n_degree = NDegree.create! valid_attributes
      get :show, {:id => n_degree.to_param}, valid_session
      assigns(:n_degree).should eq(n_degree)
    end
  end

  describe "GET new" do
    it "assigns a new n_degree as @n_degree" do
      get :new, {}, valid_session
      assigns(:n_degree).should be_a_new(NDegree)
    end
  end

  describe "GET edit" do
    it "assigns the requested n_degree as @n_degree" do
      n_degree = NDegree.create! valid_attributes
      get :edit, {:id => n_degree.to_param}, valid_session
      assigns(:n_degree).should eq(n_degree)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NDegree" do
        expect {
          post :create, {:n_degree => valid_attributes}, valid_session
        }.to change(NDegree, :count).by(1)
      end

      it "assigns a newly created n_degree as @n_degree" do
        post :create, {:n_degree => valid_attributes}, valid_session
        assigns(:n_degree).should be_a(NDegree)
        assigns(:n_degree).should be_persisted
      end

      it "redirects to the created n_degree" do
        post :create, {:n_degree => valid_attributes}, valid_session
        response.should redirect_to(NDegree.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved n_degree as @n_degree" do
        # Trigger the behavior that occurs when invalid params are submitted
        NDegree.any_instance.stub(:save).and_return(false)
        post :create, {:n_degree => {}}, valid_session
        assigns(:n_degree).should be_a_new(NDegree)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NDegree.any_instance.stub(:save).and_return(false)
        post :create, {:n_degree => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested n_degree" do
        n_degree = NDegree.create! valid_attributes
        # Assuming there are no other n_degrees in the database, this
        # specifies that the NDegree created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NDegree.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => n_degree.to_param, :n_degree => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested n_degree as @n_degree" do
        n_degree = NDegree.create! valid_attributes
        put :update, {:id => n_degree.to_param, :n_degree => valid_attributes}, valid_session
        assigns(:n_degree).should eq(n_degree)
      end

      it "redirects to the n_degree" do
        n_degree = NDegree.create! valid_attributes
        put :update, {:id => n_degree.to_param, :n_degree => valid_attributes}, valid_session
        response.should redirect_to(n_degree)
      end
    end

    describe "with invalid params" do
      it "assigns the n_degree as @n_degree" do
        n_degree = NDegree.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NDegree.any_instance.stub(:save).and_return(false)
        put :update, {:id => n_degree.to_param, :n_degree => {}}, valid_session
        assigns(:n_degree).should eq(n_degree)
      end

      it "re-renders the 'edit' template" do
        n_degree = NDegree.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NDegree.any_instance.stub(:save).and_return(false)
        put :update, {:id => n_degree.to_param, :n_degree => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested n_degree" do
      n_degree = NDegree.create! valid_attributes
      expect {
        delete :destroy, {:id => n_degree.to_param}, valid_session
      }.to change(NDegree, :count).by(-1)
    end

    it "redirects to the n_degrees list" do
      n_degree = NDegree.create! valid_attributes
      delete :destroy, {:id => n_degree.to_param}, valid_session
      response.should redirect_to(n_degrees_url)
    end
  end

end
